apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.cronJob.name }}"
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: OnFailure
          containers:
            - name: kubecost-s3-exporter
              image: {{ .Values.image.repository }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- range .Values.env }}
                - name: "{{ .name }}"
                  value: "{{ .value }}"
                {{- end }} 
