apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubecost-cid
  namespace: kubecost-cid
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kubecost-cid-service-account
          restartPolicy: OnFailure
          containers:
          - name: kubecost-cid
            image: udid/kubecost_cid
            env:
            - name: S3_BUCKET_NAME
              value: udid-kubecost
            - name: KUBECOST_API_ENDPOINT
              value: http://kubecost-eks-cost-analyzer.kubecost-eks:9090
            - name: CLUSTER_ID
              value: cluster-one
            - name: GRANULARITY
              value: hourly
            - name: PYTHONUNBUFFERED
              value: "1"
